# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/sql-server"
    config.vm.box_version = "2019.2102.2409"

    config.vm.network "private_network", type: "dhcp"

    config.vm.provider "hyperv" do |hv|
        hv.memory = 2048 
    end

    config.vm.provision "shell", inline: <<-SHELL
        iptables -A INPUT -s 192.168.1.12 -j ACCEPT # > O IP irá depender da Máquina que terá acesso à esta de testes
        iptables -A INPUT -j DROP
    SHELL
end